# Use a lightweight Node image
FROM node:18-alpine

WORKDIR /app

# Install dependencies (including devDependencies)
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose the API/Socket port
EXPOSE 5000

CMD ["npm", "run", "dev"]